### ISSUE TITLE
Can't optimize loop: Unsupported instruction (BINARY_SUBSCR, None)

### ISSUE THREAD

**Issue by daedalus** [borzunov/cpmoptimize#1]
Hi, how can i get rid of this

> Traceback (most recent call last):
>   File "code/test.py", line 231, in <module>
>     @cpmoptimize()
>   File "/usr/local/lib/python2.7/dist-packages/cpmoptimize/__init__.py", line 141, in upgrade_func
>     index += analyze_loop(settings, code, index) + 1
>   File "/usr/local/lib/python2.7/dist-packages/cpmoptimize/__init__.py", line 65, in analyze_loop
>     state = recompiler.recompile_body(settings, body)
>   File "/usr/local/lib/python2.7/dist-packages/cpmoptimize/recompiler.py", line 536, in recompile_body
>     raise RecompilationError('Unsupported instruction %s' % repr(instr), state)
> cpmoptimize.recompiler.RecompilationError: Can't optimize loop: Unsupported instruction (BINARY_SUBSCR, None) at line 253 in proccess_set, file "code/test.py"

**Comment by borzunov** [comment]
Hi @daedalus!

Looks like you're using arrays inside a loop you want to optimize. You can't do this because the optimization method works only with limited number of numeric variables.

**Comment by daedalus** [comment]
thanks
